---
title: "regressoes2"
format: html
---

```{r}
dropbox <- "c:/Users/victo/dropbox/DISSERTACAO"
library(tidyverse)
library(sf)
library(rdrobust)
```

```{r}
espaciais <- read_rds(file.path(dropbox, "dados_espaciais.rds"))
violencia <- read_rds(file.path(dropbox, "municipal.rds"))
violencia <- violencia |> 
  filter(!is.na(id_municipio))

df <- left_join(espaciais, violencia)
df <- df |> 
  mutate(taxa_homens_jovens = as.numeric(taxa_homens_jovens),
         dummy_arco_central = if_else(arcos == "Arco Central", 1, 0),
         dummy_arco_norte = if_else(arcos == "Arco Norte", 1, 0),
         dummy_arco_sul = if_else(arcos == "Arco Sul", 1, 0))

rm(espaciais, violencia)

fronteira_terrestre <- read_rds(file.path(dropbox, "fronteira_terrestre.rds"))

fronteira_interior <- read_rds(file.path(dropbox, "fronteira_interior.rds"))
```

```{r}

list1 <- list("100" = "tratamento",  "101" = "tratamento", "110" = "tratamento", "111" = "tratamento", "000" = "controle")
list2 <- list("100" = "controle",  "101" = "controle", "110" = "tratamento", "111" = "tratamento", "000" = "controle")

classificar <- function(x){purrr::pluck(list1, x)}
classificar2 <- function(x){purrr::pluck(list2, x)}

df$Grupos <- purrr::map_chr(df$label, classificar)
df$Grupo <- purrr::map_chr(df$label, classificar2)

```

```{r}
# add custom functions to extract estimates (tidy) and goodness-of-fit (glance) information
tidy.rdrobust <- function(x, ...) {
    ret <- data.frame(
      term      = "distância fronteira interior",
      estimate  = x$coef["Conventional", ],
      std.error  = x$se["Conventional", ],
      p.value = x$pv["Conventional", ])
    ret
}

glance.rdrobust <- function(x, ...) {
    ret <- data.frame(
      N_obs_treated = x$N[1],
      N_obs_control   = x$N[2])
    ret
}
```

Gráficos
```{r}
g2010 <- rdplot(df$valor_2010, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2010", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2010.png",height = 10, width = 10, units = "cm")
  
g2011 <- rdplot(df$valor_2011, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2011", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2011.png",height = 10, width = 10, units = "cm")

g2012 <- rdplot(df$valor_2012, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2012", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2012.png",height = 10, width = 10, units = "cm")

g2013 <- rdplot(df$valor_2013, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2013", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2013.png",height = 10, width = 10, units = "cm")

g2014 <- rdplot(df$valor_2014, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2014", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2014.png",height = 10, width = 10, units = "cm")

g2015 <- rdplot(df$valor_2015, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2015", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2015.png",height = 10, width = 10, units = "cm")

g2016 <- rdplot(df$valor_2016, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2016", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2016.png",height = 10, width = 10, units = "cm")

g2017 <- rdplot(df$valor_2017, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2017", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2017.png",height = 10, width = 10, units = "cm")

g2018 <- rdplot(df$valor_2018, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2018", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2018.png",height = 10, width = 10, units = "cm")

g2019 <- rdplot(df$valor_2019, (df$distancia_fronteira_interior)/1000, c=0, p=1,
     title = "2019", 
     y.label = "Homicídios por 100 mil hab.", 
     x.label = "Distância (km)")
ggsave("g2019.png",height = 10, width = 10, units = "cm")

```

```{r}

MinMax <- function(x) paste0('[', min(x, na.rm = TRUE), ', ', max(x, na.rm = TRUE), ']')

library(modelsummary)

datasummary(taxa_analfabetismo+taxa_desemprego+gini+pibpc+taxa_renda_pobre+taxa_trab_infantil+taxa_homens_jovens ~ groups*(Mean + SD+MinMax),
            data = df,
            output = "latex")

datasummary(taxa_analfabetismo+taxa_desemprego+gini+pibpc+taxa_renda_pobre+taxa_trab_infantil+taxa_homens_jovens ~ arcos*(Mean + SD+MinMax),
            data = df,
            output = "latex")

datasummary(valor_2010+valor_2011+valor_2012+valor_2013+valor_2014+valor_2015+valor_2016+valor_2017+valor_2018+valor_2019 ~ groups*(Mean +SD+MinMax),
            data = df,
            output = "latex")

datasummary(valor_2010+valor_2011+valor_2012+valor_2013+valor_2014+valor_2015+valor_2016+valor_2017+valor_2018+valor_2019 ~ arcos*(Mean +SD+MinMax),
            data = df,
            output = "latex")



```





Distância dos municípios da divisão entre tratamento e controle

```{r}
df5 <- df
  
socioecon <- df5 |> 
  select(taxa_analfabetismo:taxa_homens_jovens)

st_geometry(socioecon) <- NULL

geograficas <- df5 |> 
  select(latitude, longitude, dummy_arco_central, dummy_arco_norte)

st_geometry(geograficas) <- NULL

all <- df5 |> 
  select(taxa_analfabetismo:taxa_homens_jovens, latitude, longitude, dummy_arco_central, dummy_arco_norte)

st_geometry(all) <- NULL

df5_norte <- df5 |> 
  filter(arcos == "Arco Norte")
  
df5_central <- df5 |> 
  filter(arcos == "Arco Central")

df5_sul <- df5 |> 
  filter(arcos == "Arco Sul")

all_norte <- df5_norte |> 
  select(taxa_analfabetismo:taxa_homens_jovens, latitude, longitude)

st_geometry(all_norte) <- NULL

all_central <- df5_central |> 
  select(taxa_analfabetismo:taxa_homens_jovens, latitude, longitude)

st_geometry(all_central) <- NULL

all_sul <- df5_sul |> 
  select(taxa_analfabetismo:taxa_homens_jovens, latitude, longitude)

st_geometry(all_sul) <- NULL

```

```{r}
anos5 <- list(
  "ano 2010" = rdrobust(y = df5$valor_2010, x = df5$distancia_fronteira_interior, c = 0, covs = all),
  "ano 2011" = rdrobust(y = df5$valor_2011, x = df5$distancia_fronteira_interior, c = 0, covs = all),
  "ano 2012" = rdrobust(y = df5$valor_2012, x = df5$distancia_fronteira_interior, c = 0, covs = all),
  "ano 2013" = rdrobust(y = df5$valor_2013, x = df5$distancia_fronteira_interior, c = 0, covs = all),
  "ano 2014" = rdrobust(y = df5$valor_2014, x = df5$distancia_fronteira_interior, c = 0, covs = all))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T)

anos5 <- list(
  "ano 2015" = rdrobust(y = df5$valor_2015, x = df5$distancia_fronteira_interior, c = 0, covs = all),
  "ano 2016" = rdrobust(y = df5$valor_2016, x = df5$distancia_fronteira_interior, c = 0, covs = all),
  "ano 2017" = rdrobust(y = df5$valor_2017, x = df5$distancia_fronteira_interior, c = 0, covs = all),
  "ano 2018" = rdrobust(y = df5$valor_2018, x = df5$distancia_fronteira_interior, c = 0, covs = all),
  "ano 2019" = rdrobust(y = df5$valor_2019, x = df5$distancia_fronteira_interior, c = 0, covs = all))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T
                           )
```

```{r}
anos5 <- list(
  "ano 2010" = rdrobust(y = df5_norte$valor_2010, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte),
  "ano 2011" = rdrobust(y = df5_norte$valor_2011, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte),
  "ano 2012" = rdrobust(y = df5_norte$valor_2012, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte),
  "ano 2013" = rdrobust(y = df5_norte$valor_2013, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte),
  "ano 2014" = rdrobust(y = df5_norte$valor_2014, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")

anos5 <- list(
  "ano 2015" = rdrobust(y = df5_norte$valor_2015, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte),
  "ano 2016" = rdrobust(y = df5_norte$valor_2016, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte),
  "ano 2017" = rdrobust(y = df5_norte$valor_2017, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte),
  "ano 2018" = rdrobust(y = df5_norte$valor_2018, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte),
  "ano 2019" = rdrobust(y = df5_norte$valor_2019, x = df5_norte$distancia_fronteira_interior, c = 0, covs = all_norte))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")
```

```{r}
anos5 <- list(
  "ano 2010" = rdrobust(y = df5_central$valor_2010, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central),
  "ano 2011" = rdrobust(y = df5_central$valor_2011, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central),
  "ano 2012" = rdrobust(y = df5_central$valor_2012, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central),
  "ano 2013" = rdrobust(y = df5_central$valor_2013, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central),
  "ano 2014" = rdrobust(y = df5_central$valor_2014, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")

anos5 <- list(
  "ano 2015" = rdrobust(y = df5_central$valor_2015, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central),
  "ano 2016" = rdrobust(y = df5_central$valor_2016, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central),
  "ano 2017" = rdrobust(y = df5_central$valor_2017, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central),
  "ano 2018" = rdrobust(y = df5_central$valor_2018, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central),
  "ano 2019" = rdrobust(y = df5_central$valor_2019, x = df5_central$distancia_fronteira_interior, c = 0, covs = all_central))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")
```

```{r}
anos5 <- list(
  "ano 2010" = rdrobust(y = df5_sul$valor_2010, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul),
  "ano 2011" = rdrobust(y = df5_sul$valor_2011, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul),
  "ano 2012" = rdrobust(y = df5_sul$valor_2012, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul),
  "ano 2013" = rdrobust(y = df5_sul$valor_2013, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul),
  "ano 2014" = rdrobust(y = df5_sul$valor_2014, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")

anos5 <- list(
  "ano 2015" = rdrobust(y = df5_sul$valor_2015, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul),
  "ano 2016" = rdrobust(y = df5_sul$valor_2016, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul),
  "ano 2017" = rdrobust(y = df5_sul$valor_2017, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul),
  "ano 2018" = rdrobust(y = df5_sul$valor_2018, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul),
  "ano 2019" = rdrobust(y = df5_sul$valor_2019, x = df5_sul$distancia_fronteira_interior, c = 0, covs = all_sul))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")
```

```{r}
anos5 <- list(
  "ano 2010" = rdrobust(y = df5$valor_2010, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all),
  "ano 2011" = rdrobust(y = df5$valor_2011, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all),
  "ano 2012" = rdrobust(y = df5$valor_2012, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all),
  "ano 2013" = rdrobust(y = df5$valor_2013, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all),
  "ano 2014" = rdrobust(y = df5$valor_2014, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")

anos5 <- list(
  "ano 2015" = rdrobust(y = df5$valor_2015, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all),
  "ano 2016" = rdrobust(y = df5$valor_2016, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all),
  "ano 2017" = rdrobust(y = df5$valor_2017, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all),
  "ano 2018" = rdrobust(y = df5$valor_2018, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all),
  "ano 2019" = rdrobust(y = df5$valor_2019, x = df5$distancia_fronteira_interior, c = 0, p=2,  covs = all))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")
```

```{r}
anos5 <- list(
  "ano 2010" = rdrobust(y = df5_norte$valor_2010, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte),
  "ano 2011" = rdrobust(y = df5_norte$valor_2011, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte),
  "ano 2012" = rdrobust(y = df5_norte$valor_2012, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte),
  "ano 2013" = rdrobust(y = df5_norte$valor_2013, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte),
  "ano 2014" = rdrobust(y = df5_norte$valor_2014, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")

anos5 <- list(
  "ano 2015" = rdrobust(y = df5_norte$valor_2015, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte),
  "ano 2016" = rdrobust(y = df5_norte$valor_2016, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte),
  "ano 2017" = rdrobust(y = df5_norte$valor_2017, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte),
  "ano 2018" = rdrobust(y = df5_norte$valor_2018, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte),
  "ano 2019" = rdrobust(y = df5_norte$valor_2019, x = df5_norte$distancia_fronteira_interior, c = 0, p=2,  covs = all_norte))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")
```

```{r}
anos5 <- list(
  "ano 2010" = rdrobust(y = df5_central$valor_2010, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central),
  "ano 2011" = rdrobust(y = df5_central$valor_2011, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central),
  "ano 2012" = rdrobust(y = df5_central$valor_2012, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central),
  "ano 2013" = rdrobust(y = df5_central$valor_2013, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central),
  "ano 2014" = rdrobust(y = df5_central$valor_2014, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")

anos5 <- list(
  "ano 2015" = rdrobust(y = df5_central$valor_2015, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central),
  "ano 2016" = rdrobust(y = df5_central$valor_2016, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central),
  "ano 2017" = rdrobust(y = df5_central$valor_2017, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central),
  "ano 2018" = rdrobust(y = df5_central$valor_2018, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central),
  "ano 2019" = rdrobust(y = df5_central$valor_2019, x = df5_central$distancia_fronteira_interior, c = 0, p=2,  covs = all_central))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")
```

```{r}
anos5 <- list(
  "ano 2010" = rdrobust(y = df5_sul$valor_2010, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul),
  "ano 2011" = rdrobust(y = df5_sul$valor_2011, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul),
  "ano 2012" = rdrobust(y = df5_sul$valor_2012, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul),
  "ano 2013" = rdrobust(y = df5_sul$valor_2013, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul),
  "ano 2014" = rdrobust(y = df5_sul$valor_2014, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")

anos5 <- list(
  "ano 2015" = rdrobust(y = df5_sul$valor_2015, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul),
  "ano 2016" = rdrobust(y = df5_sul$valor_2016, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul),
  "ano 2017" = rdrobust(y = df5_sul$valor_2017, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul),
  "ano 2018" = rdrobust(y = df5_sul$valor_2018, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul),
  "ano 2019" = rdrobust(y = df5_sul$valor_2019, x = df5_sul$distancia_fronteira_interior, c = 0, p=2,  covs = all_sul))

modelsummary::modelsummary(anos5,
                           statistic = 'std.error',
                           stars = T,
                           output = "latex")
```

```{r}
df2 <- df |> 
  filter(label %in% c("101", "111", "000"))

modelo2 <- lm(valor_2019 ~ Grupos + taxa_analfabetismo + taxa_desemprego + gini + pibpc + taxa_renda_pobre + taxa_trab_infantil + taxa_homens_jovens + latitude + longitude + arcos, data = df2)

modelsummary::modelsummary(modelo2,
                           stars = T)
```

```{r}
df3 <- df |> 
  filter(label %in% c("101", "111", "100", "101"))

modelo3 <- lm(valor_2019 ~ Grupo + taxa_analfabetismo + taxa_desemprego + gini + pibpc + taxa_renda_pobre + taxa_trab_infantil + taxa_homens_jovens + latitude + longitude + arcos, data = df3)

modelsummary::modelsummary(modelo3,
                           stars = T)
```

```{r}
df4 <- df |> 
  filter(label %in% c("100", "101", "000"))

modelo4 <- lm(valor_2019 ~ Grupos + taxa_analfabetismo + taxa_desemprego + gini + pibpc + taxa_renda_pobre + taxa_trab_infantil + taxa_homens_jovens + latitude + longitude + arcos, data = df4)

modelsummary::modelsummary(modelo4,
                           stars = T)
```

```{r}
modelsummary::modelsummary(list("exclui sedes fora da FF" = modelo2,
                                "efeito fronteira" = modelo3,
                                "efeito forças armadas" = modelo4),
                           stars = T,
                           output = "latex")
```


