---
title: "spatialrdd"
format: html
---

```{r}
dropbox <- "c:/Users/victor/dropbox/DISSERTACAO"
library(SpatialRDD)
library(tidyverse)
library(sf)
library(modelsummary)
library(geobr)
library(nngeo)
library(palettetown)

```

```{r}
espaciais <- read_rds(file.path(dropbox, "dados_espaciais.rds"))
violencia <- read_rds(file.path(dropbox, "municipal.rds"))
violencia <- violencia |> 
  filter(!is.na(id_municipio))

df <- left_join(espaciais, violencia)
df <- df |> 
  mutate(taxa_homens_jovens = as.numeric(taxa_homens_jovens))

rm(violencia)

fronteira_terrestre <- read_rds(file.path(dropbox, "fronteira_terrestre.rds"))

fronteira_interior <- read_rds(file.path(dropbox, "fronteira_interior.rds"))
```

```{r}
espaciais <- read_rds(file.path(dropbox, "dados_espaciais.rds"))
 
full <- st_union(espaciais)

full <- st_remove_holes(full)

treated <- st_union(filter(espaciais, groups == "treatment"))
treated <- st_sf(treated)
treated <- st_remove_holes(treated)
```

```{r}

points <- read_municipal_seat(year=2010, showProgress = T) %>%
  st_transform("WGS84") |> 
  rename("id_municipio" = "code_muni",
         "nome" = "name_muni",
         "id_uf" = "code_state",
         'sigla_uf' = "abbrev_state",
         "nome_regiao" = "name_region",
         "id_regiao" = "code_region",
         "ano" = "year") |> 
  mutate(id_municipio = as.character(id_municipio))

t <- select(espaciais, id_municipio, groups)
st_geometry(t) <- NULL

points <- points |> 
  right_join(t, by="id_municipio")

rm(t)
```


```{r}
ggplot()+
  geom_sf(data = full, fill = "lightgray")+
  geom_sf(data =  treated, , fill = "gray")+
  geom_sf(data = fronteira_interior, color = "red")+
  geom_sf(data = points, mapping = aes(colour = groups), size = 0.1) +
  scale_color_poke(pokemon = 'charizard', spread = 2, name = "Grupo", labels = c("Controle", "Tratamento"))+
  theme_minimal()

ggsave("sedes_municipais.png",height = 20, width = 20, units = "cm")
```

```{r}
ggplot()+
  geom_sf(data = espaciais, aes(fill = arcos))+
  scale_fill_poke(pokemon = 'charizard', spread = 3, name = "Arcos", labels = c("Central", "Norte", "Sul"))+
  theme_minimal()

ggsave("arcos.png",height = 20, width = 20, units = "cm")
```



```{r}

points <- points |> 
  left_join(violencia |> select(id_municipio, valor_2010:valor_2019))

list("2010"=lm(valor_2010 ~ treated, data = points)) |> 
  modelsummary(stars = T)
```


