{
  "hash": "783dee71f726ec8705338633857de8a0",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: pdf\n\n# misc\nlang: pt-BR # siga o padrão: pt-BR, es-AR, en-US etc.\neditor: source\n---\n\n\n\n# Arco Norte\n\n\n\n\n\n\n\n\n\n## Contexto\n\nO Arco Norte da faixa de fronteira brasileira é constituído de 69 municípios, classificados aqui como tratamento. Com a proposta de expansão 22 municípios passariam a fazer parte da faixa de fronteira e são classificados aqui como grupo de controle. Utilizando o método de **Regressão Descontínua (RD)**, buscamos identificar se a presença militar próximo à fronteira está associada a variações significativas nos indicadores de violência, especificamente o número de mortes violentas por 100 mil habitantes.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](arco_norte_files/figure-pdf/unnamed-chunk-3-1.png)\n:::\n:::\n\n\n\nA **variável de cutoff** utilizada é a distância em relação ao limite entre tratamento e controle, sendo o ponto de corte (cutoff) igual a zero. O grupo de tratamento é composto por municípios próximos à fronteira (valores negativos), onde há presença das Forças Armadas, enquanto os municípios mais distantes (valores positivos) compõem o grupo de controle, sem a presença militar.\n\n## Resultados Principais\n\n### Mortes violentas\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](arco_norte_files/figure-pdf/unnamed-chunk-4-1.png)\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\\tiny\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nSharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   71\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   51           20\nEff. Number of Obs.              16           15\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               65320.510    65320.510\nBW bias (b)               90618.529    90618.529\nrho (h/b)                     0.721        0.721\nUnique Obs.                      51           20\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    15.357     7.159     2.145     0.032     [1.326 , 29.388]    \n        Robust         -         -     1.950     0.051    [-0.087 , 33.164]    \n=============================================================================\n```\n\n\n:::\n:::\n\n\n\n\\normalsize\nA análise revelou que o grupo de tratamento está associada a uma redução significativa no número de mortes violentas por 100 mil habitantes em municípios próximos à fronteira. O coeficiente estimado é de 15.35 mortes violentas a menos no grupo de tratamento (municípios com presença militar) em comparação com o grupo de controle. Essa conclusão se baseia na interpretação de Huntington-Klein (2021), que recomenda a inversão da interpretação do coeficiente em cenários onde o tratamento está à esquerda do cutoff.\n\n### Falsificação\n\nOs testes de placebo têm como objetivo verificar se há um efeito significativo em cutoffs falsos, isto é, cutoffs em pontos onde você não espera encontrar um efeito real. Se os resultados para esses cutoffs falsos forem insignificantes, isso reforça a validade do cutoff original (zero) utilizado na análise.\n\n\\tiny\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Resultados para o teste com limiar mais à esquerda\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   71\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   35           36\nEff. Number of Obs.               2            8\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               34785.575    34785.575\nBW bias (b)               72565.637    72565.637\nrho (h/b)                     0.479        0.479\nUnique Obs.                      35           36\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    26.133    40.587     0.644     0.520   [-53.416 , 105.682]   \n        Robust         -         -     0.723     0.470   [-61.739 , 133.841]   \n=============================================================================\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Resultados para o teste com limiar mais à direita\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   71\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   65            6\nEff. Number of Obs.              17            5\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               59552.451    59552.451\nBW bias (b)               82445.017    82445.017\nrho (h/b)                     0.722        0.722\nUnique Obs.                      65            6\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    -3.759     5.709    -0.659     0.510   [-14.949 , 7.430]     \n        Robust         -         -     0.611     0.541    [-9.498 , 18.105]    \n=============================================================================\n```\n\n\n:::\n:::\n\n\n\n\\normalsize\nPara o cutoff falso de -50 km, o p-valor indica que esse coeficiente não é estatisticamente significativo. O intervalo de confiança \\[−53.416, 105.682\\] é amplo e inclui zero, sugerindo que não há um efeito claro nesse ponto. Já para o cutoff falso de 50 km, o p-valor também é muito alto, indicando nenhum efeito significativo. O intervalo de confiança \\[−14.949, 7.430\\] também inclui zero, reforçando a falta de evidência para um efeito neste ponto. Ambos os cutoffs falsos (-50 km e 50 km) apresentaram coeficientes insignificantes, com p-valores muito altos. Isso sugere que não há efeitos significativos fora do cutoff real (zero), corroborando a validade da escolha do cutoff correto no modelo original. Isso fortalece a confiança de que o efeito observado no cutoff verdadeiro (zero) é real e não um artefato do modelo.\n\nA análise revelou que o pertencimento à Faixa de Fronteira está associado a uma redução significativa no número de mortes violentas por 100 mil habitantes em municípios próximos à fronteira. O coeficiente estimado é de 12,29 mortes violentas a menos no grupo de tratamento (municípios com presença militar) em comparação com o grupo de controle. Essa conclusão se baseia na interpretação de Huntington-Klein (2021), que recomenda a inversão da interpretação do coeficiente em cenários onde o tratamento está à esquerda do cutoff.\n\n### Controles\n\nApesar do modelo de RD ser capaz de determinar o efeito do tratamento com relativa segurança sem aplicar outras variáveis de controle, existe a possibilidade de o fazer para verificar a heterogeneidade de efeitos. Apresenta-se aqui a interação da variável de distância entre tratamento/controle com variáveis socioeconômicas. A análise mostra que o impacto da atuação militar varia conforme características socioeconômicas dos municípios:\n\n\\tiny\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   71\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   51           20\nEff. Number of Obs.              16           15\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               55081.311    55081.311\nBW bias (b)               88173.905    88173.905\nrho (h/b)                     0.625        0.625\nUnique Obs.                      51           20\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    12.290     5.530     2.222     0.026     [1.452 , 23.128]    \n        Robust         -         -     2.478     0.013     [3.466 , 29.696]    \n=============================================================================\n```\n\n\n:::\n:::\n\n\n\n\\normalsize\nAo incluir as variáveis moderadoras (a saber: taxa de analfabetismo, PIB per capita, taxa de desemprego, índice de Gini, e percentuais de baixa renda, homens jovens e trabalho infantil), a magnitude do efeito diminui de 15.357 para 12.290 mortes violentas a menos por 100 mil habitantes. Isso sugere que parte do efeito inicial observado no modelo sem moderadores era explicado por diferenças socioeconômicas entre os municípios. Mesmo após o controle por essas variáveis, o efeito do pertencimento à Faixa de Fronteira na redução das mortes violentas permanece significativo e robusto, o que indica que a atuação de forças de segurança na região tem um impacto independente.\n\nPode-se afirmar, portanto que estar na Feixa de Fronteira contribui para a redução nas mortes violentas. Parte dessa redução está relacionada com características socioeconômicas dos municípios, sugerindo que os municípios mais vulneráveis podem estar se beneficiando de maneira mais significativa da presença das forças de segurança que atuam na região. Mesmo após o controle por vulnerabilidades socioeconômicas, o efeito continua significativo, o que sugere um impacto robusto na redução da violência.\n\n## Homicídios\n\nAo analisar o efeito sobre a quantidade de homicídios por 100 mil habitantes, somente os anos de 2011, 2012 e 2017 não apresentaram efeito significativo. Nos anos de 2010 e 2015, os efeitos são marginalmente significativos, sugerindo uma tendência de redução, embora não robusta e em todos os outros houveram efeitos significativos. Estes estimadores apontam efeitos de 33,4, 34,6, 56,2, 52,1 e 32,5 homicícios por 100 mil habitantes a menos no grupo de tratamento na Região Norte. Esses resultados sugerem que, em determinados anos, compor da faixa de fronteira resultou em uma redução significativa nos homicídios, com maior robustez nos últimos anos da série analisada (2018 e 2019).\n\n\\tiny\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n### Resultados para a variável: valor_2010 \nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   77\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   56           21\nEff. Number of Obs.              19           14\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               48446.943    48446.943\nBW bias (b)               84982.292    84982.292\nrho (h/b)                     0.570        0.570\nUnique Obs.                      56           21\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    31.750    17.796     1.784     0.074    [-3.129 , 66.628]    \n        Robust         -         -     1.567     0.117    [-9.198 , 82.549]    \n=============================================================================\nNULL\n\n\n### Resultados para a variável: valor_2013 \nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   77\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   56           21\nEff. Number of Obs.              19           14\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               47325.479    47325.479\nBW bias (b)               83904.409    83904.409\nrho (h/b)                     0.564        0.564\nUnique Obs.                      56           21\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    33.374    15.949     2.092     0.036     [2.113 , 64.634]    \n        Robust         -         -     1.667     0.095    [-6.192 , 76.781]    \n=============================================================================\nNULL\n\n\n### Resultados para a variável: valor_2014 \nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   77\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   56           21\nEff. Number of Obs.              19           14\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               46803.944    46803.944\nBW bias (b)               81928.604    81928.604\nrho (h/b)                     0.571        0.571\nUnique Obs.                      56           21\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    34.614    12.735     2.718     0.007     [9.653 , 59.575]    \n        Robust         -         -     1.917     0.055    [-0.720 , 64.661]    \n=============================================================================\nNULL\n\n\n### Resultados para a variável: valor_2015 \nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   77\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   56           21\nEff. Number of Obs.              19           14\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               48273.825    48273.825\nBW bias (b)               81082.724    81082.724\nrho (h/b)                     0.595        0.595\nUnique Obs.                      56           21\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    30.884    19.561     1.579     0.114    [-7.454 , 69.223]    \n        Robust         -         -     1.127     0.260   [-22.275 , 82.555]    \n=============================================================================\nNULL\n\n\n### Resultados para a variável: valor_2016 \nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   77\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   56           21\nEff. Number of Obs.              19           14\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               46989.072    46989.072\nBW bias (b)               82557.787    82557.787\nrho (h/b)                     0.569        0.569\nUnique Obs.                      56           21\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    56.232    25.404     2.214     0.027     [6.442 , 106.022]   \n        Robust         -         -     1.685     0.092    [-9.381 , 124.177]   \n=============================================================================\nNULL\n\n\n### Resultados para a variável: valor_2018 \nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   77\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   56           21\nEff. Number of Obs.              19           14\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               46913.238    46913.238\nBW bias (b)               82942.181    82942.181\nrho (h/b)                     0.566        0.566\nUnique Obs.                      56           21\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    52.136    11.171     4.667     0.000    [30.242 , 74.031]    \n        Robust         -         -     3.911     0.000    [26.455 , 79.614]    \n=============================================================================\nNULL\n\n\n### Resultados para a variável: valor_2019 \nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   77\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   56           21\nEff. Number of Obs.              19           14\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               47627.744    47627.744\nBW bias (b)               83042.592    83042.592\nrho (h/b)                     0.574        0.574\nUnique Obs.                      56           21\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    32.502     6.874     4.728     0.000    [19.030 , 45.974]    \n        Robust         -         -     3.601     0.000    [14.386 , 48.752]    \n=============================================================================\nNULL\n```\n\n\n:::\n:::\n\n\n\n\\normalsize\n## Outros crimes\n\nAo analisar o efeito estatisticamente significante foi verificado somente nas mortes no trânsito e em crimes e nas mortes a esclarecer.\n\nEm relação às mortes no transito, o estimadores aponta efeitos de 21,9 mortes no trânsito por 100 mil habitantes a menos no grupo de tratamento na Região Norte. Já para mortes a esclarecer, o efeito é de 1,9 a menos. Todas as outras variáveis são rejeitadas a um nível de 5%\n\n\\tiny\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n### Resultados para a variável: transito \nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   77\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   56           21\nEff. Number of Obs.              19           14\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               49089.722    49089.722\nBW bias (b)               86217.197    86217.197\nrho (h/b)                     0.569        0.569\nUnique Obs.                      56           21\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional    21.898     4.347     5.037     0.000    [13.377 , 30.419]    \n        Robust         -         -     4.528     0.000    [13.594 , 34.345]    \n=============================================================================\nNULL\n\n\n### Resultados para a variável: esclarecer \nCovariate-adjusted Sharp RD estimates using local polynomial regression.\n\nNumber of Obs.                   77\nBW type                       mserd\nKernel                   Triangular\nVCE method                       NN\n\nNumber of Obs.                   56           21\nEff. Number of Obs.              19           14\nOrder est. (p)                    1            1\nOrder bias  (q)                   2            2\nBW est. (h)               48261.588    48261.588\nBW bias (b)               83436.787    83436.787\nrho (h/b)                     0.578        0.578\nUnique Obs.                      56           21\n\n=============================================================================\n        Method     Coef. Std. Err.         z     P>|z|      [ 95% C.I. ]       \n=============================================================================\n  Conventional     1.887     0.749     2.520     0.012     [0.419 , 3.354]     \n        Robust         -         -     2.292     0.022     [0.327 , 4.188]     \n=============================================================================\nNULL\n```\n\n\n:::\n:::\n\n\n\n\\normalsize\n\n## Discussão dos Resultados\n\nEsses achados sugerem que o pertencimento à Faixa de Fronteira tem um efeito protetor sobre a segurança pública nas áreas de fronteira. Em particular, essa situação foi mais eficaz em reduzir a violência em municípios mais vulneráveis, como aqueles com maior pobreza, desigualdade e analfabetismo.\n",
    "supporting": [
      "arco_norte_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}