---
format: pdf

# misc
lang: pt-BR # siga o padrão: pt-BR, es-AR, en-US etc.
editor: source
---

# Fundamentação Teórica

## Contexto geopolítico da Faixa de Fronteira

A faixa de até 150 quilômetros de largura ao longo das fronteiras terrestres, conforme descrito no art. 20 da Constituição Federal de 1988, é uma região de interesse especial para o Estado brasileiro, sendo objeto de muitas regulamentações ao longo dos anos. A Lei 601, de 18 de setembro de 1850, é considerada a primeira regulamentação da região, estabelecendo a largura em dez léguas ao longo dos limites fronteiriços, o que equivale a 66 quilômetros.

Na Constituição, a primeira vez que a faixa de fronteira é objeto de regulamentação ocorre em 1934, na seção de Segurança Nacional, estabelecida com 100 quilômetros de largura ao longo dos limites terrestres. No artigo 166, determina-se que todas as concessões de terras e aberturas de vias de comunicação dentro dessa faixa não poderiam ser efetivadas sem audiência do Conselho Superior de Segurança Nacional. Essa norma demonstra a preocupação do legislador com a expansão populacional, especialmente na Região Norte. Em seguida, na Constituição de 1937, as exigências para a região são basicamente repetidas, porém, com um acréscimo: a faixa de fronteira passa a ter 150 quilômetros de largura, medida atualmente utilizada para sua demarcação.

A Constituição Federal de 1988 trata da faixa de fronteira em três pontos distintos. Primeiramente, no art. 20, que trata dos bens da União, ela é definida como a faixa de até cento e cinquenta quilômetros de largura ao longo das fronteiras terrestres, descrita como fundamental para a defesa do território nacional, sendo sua ocupação e utilização reguladas por lei. Depois, no art. 91, que trata do Conselho de Defesa Nacional, é descrito que é de competência do órgão propor os critérios e condições de utilização de áreas indispensáveis à segurança do território nacional e opinar sobre seu efetivo uso, especialmente na faixa de fronteira. Por último, no art. 176, ao descrever as condições de pesquisa e lavra de recursos minerais e o aproveitamento de potenciais de energia hidráulica, determina que tais atividades só poderão ser efetuadas mediante autorização ou concessão da União, com condições específicas quando essas atividades se desenvolverem na faixa de fronteira ou em terras indígenas.

A fim de corresponder à atenção devida à faixa de fronteira conforme a Constituição, a atuação das Forças Armadas na região está também descrita em diferentes leis ao longo da história. @safira_maria_de_figueredo_operacao_2017 destaca quatro marcos normativos fundamentais que regulamentam a atuação das Forças Armadas na faixa de fronteira brasileira: a Constituição Federal, o Programa Nacional de Defesa, a Lei Complementar nº 97/1999 e o Programa de Proteção Integrada das Fronteiras, que inclui a Operação Ágata. A Constituição Federal estabelece a importância estratégica da faixa de fronteira e o papel das Forças Armadas na defesa do território nacional. O Programa Nacional de Defesa é o documento orientador do planejamento de ações destinadas à defesa nacional, coordenadas pelo Ministério da Defesa, e tem entre suas prioridades a vigilância das fronteiras, a proteção do meio ambiente e o uso sustentável dos recursos, aspectos essenciais para o desenvolvimento e a integração da Amazônia. A Lei Complementar nº 97/1999 regulamenta o emprego das Forças Armadas, permitindo sua atuação em regiões fronteiriças quando necessário. Por fim, o Programa de Proteção Integrada das Fronteiras, por meio da Operação Ágata, promove a cooperação entre diferentes agências governamentais para o controle das fronteiras e o combate a atividades ilícitas transnacionais.

O terceiro marco normativo, a Lei Complementar nº 97/1999, dispõe sobre as normas gerais para a organização, o preparo e o emprego das Forças Armadas. O artigo 16 estabelece sua atuação como subsidiária, cooperando com o desenvolvimento nacional e a defesa civil. Com as inclusões trazidas pela Lei Complementar nº 136/2010, atribui-se às Forças Armadas a atuação, por meio de ações preventivas e repressivas, na faixa de fronteira terrestre, no mar e nas águas interiores, independentemente da posse, da propriedade, da finalidade ou de qualquer gravame que sobre ela recaia, contra delitos transfronteiriços e ambientais, isoladamente ou em coordenação com outros órgãos do Poder Executivo, executando, dentre outras, as ações de:

1.  patrulhamento;
2.  revista de pessoas, veículos terrestres, embarcações e aeronaves; e
3.  prisões em flagrante delito.

Levando em consideração a interpretação constitucional do papel das Forças Armadas na Garantia da Lei e da Ordem (GLO) e das seis possibilidades constitucionalmente legítimas (intervenção federal, estado de defesa, estado de sítio, segurança em eventos oficiais públicos, policiamento ostensivo por solicitação do governo do estado e realização de diligências determinadas em inquérito policial militar), @safira_maria_de_figueredo_operacao_2017 considera que, a partir da Lei Complementar nº 97/1999, surgiu a sétima atividade de segurança pública para Garantia da Lei e da Ordem atribuída às Forças Armadas: a atuação na faixa de fronteira, com poder de polícia explícito, nas ações de patrulhamento, revista de pessoas, veículos, embarcações e aeronaves, apreensão de objetos de crime e prisão em flagrante delito.

@safira_maria_de_figueredo_operacao_2017 também explora o fato de que a atuação das Forças Armadas na faixa de fronteira difere das situações comuns para atuar na Garantia da Lei e da Ordem. O procedimento normal deve cumprir três princípios: a decisão do Presidente da República, o esgotamento dos instrumentos destinados à preservação da ordem pública e a formalização, reconhecendo tais instrumentos como indisponíveis, inexistentes ou insuficientes. Distintamente do que ocorre com as atividades de Garantia da Lei e da Ordem elencadas no artigo 15 da Lei Complementar nº 97/99, nas atividades contra o crime na faixa de fronteira não há a exigência de declaração de esgotamento dos órgãos ou instrumentos de preservação da segurança pública, mas, como se trata de atividade subsidiária, está implícito que as Forças Armadas só podem atuar no combate aos crimes na ausência das instituições incumbidas constitucionalmente de tais atribuições.

A materialização da atuação das Forças Armadas na faixa de fronteira se dá no combate ao crime transfronteiriço. A Portaria nº 061/2005 do Exército Brasileiro considera como crimes transfronteiriços:

-   A entrada (e/ou tentativa de saída) ilegal no território nacional de armas, munições, explosivos e demais produtos afins;
-   Tráfico ilícito de entorpecentes e/ou substâncias que determinam dependência física ou psíquica, ou matéria-prima destinada à sua preparação;
-   O contrabando e o descaminho (Código Penal Brasileiro, art. 334);
-   O tráfico de plantas e de animais, conforme a Lei de Crimes Ambientais (Lei 9.605/98) e o Código de Proteção à Fauna (Lei 5.197/67);
-   A entrada (e/ou tentativa de saída) no território nacional de vetores em desacordo com as normas de vigilância epidemiológica;
-   A prática de atos lesivos ao meio ambiente, conforme definido na Lei de Crimes Ambientais (Lei nº 9.605/98);
-   A exploração predatória ou ilegal de recursos naturais; e
-   A prática de atos lesivos à diversidade e à integridade do patrimônio genético do país, conforme a Medida Provisória nº 2.186-16, de 23 de agosto de 2001 (revogada pela Lei nº 13.123, de 20 de maio de 2015).

Como explorado anteriormente, as Forças Armadas possuem capacidade para organizar operações de combate a esses crimes na faixa de fronteira. Exemplos recentes incluem a Operação Ágata e o Programa VIGIA, atualmente Guardiões da Fronteira. @safira_maria_de_figueredo_operacao_2017 considera a Operação Ágata um marco importante para o desenvolvimento da segurança pública na região.

@fagundes_politicas_2019 e @safira_maria_de_figueredo_operacao_2017 concordam que o poder de polícia das Forças Armadas na faixa de fronteira se distingue das operações de Garantia da Lei e da Ordem (GLO) em aspectos significativos. Fagundes observa que o Exército Brasileiro possui autonomia para atuar preventivamente e repressivamente contra delitos transfronteiriços na faixa de fronteira sem a necessidade de uma ordem direta do Presidente da República, o que é uma diferença importante em relação às operações de GLO, que exigem essa autorização executiva em situações onde as forças de segurança tradicionais se mostram insuficientes. Similarmente, Figueiredo aponta que, na faixa de fronteira, as Forças Armadas possuem um poder de polícia contínuo e explícito, permitindo ações de patrulhamento e revistas de forma mais abrangente e menos restrita em comparação com o caráter episódico e limitado das operações de GLO, que são focadas em restaurar a ordem pública temporariamente em áreas específicas. Essa distinção destaca o papel das Forças Armadas como uma presença permanente e preventiva na fronteira, em vez de uma força reativa apenas em contextos emergenciais.

## Dinâmica de segurança pública nas regiões de fronteira

Analisar o problema da segurança pública na faixa de fronteira exige considerar primeiramente a grande extensão da região. Na configuração atual, a faixa de fronteira ocupa 27% do território brasileiro, correndo ao largo de 16.886 quilômetros de fronteira terrestre. Há 588 municípios na faixa de fronteira, pertencentes a 11 estados.

| Arco                        | Número de municípios |
|-----------------------------|----------------------|
| Norte (AC, AM, AP, PA e RR) | 71                   |
| Central (MS, MT e RO)       | 99                   |
| Sul (PR, RS e SC)           | 418                  |
| **Total**                   | **588**              |

: Municípios na Faixa de Fronteira por Arco

Essa grande extensão geográfica naturalmente carrega uma significativa heterogeneidade. As diferentes partes da faixa de fronteira, portanto, têm características próprias que influenciam o tipo de problema que enfrentam na segurança pública. Para cada arco, a literatura aponta crimes específicos favorecidos pelas condições geográficas e socioeconômicas do lugar, apesar de concordar que o tráfico de drogas, o contrabando e a exploração ambiental são comuns em todas as regiões.

No arco Norte, o trabalho de @dias_dinamica_2024 analisa a dinâmica de violência e o papel das facções criminais na macrorregião. O artigo detalha como a expansão e o confronto entre facções, como o PCC e o Comando Vermelho (CV), moldaram a criminalidade e a violência na região Norte e discute o impacto direto dessas facções em áreas específicas, relacionando sua presença ao aumento da violência. O texto explora como facções se associam a atividades ilegais típicas da região, como o tráfico de drogas e os crimes ambientais, incluindo extração ilegal de madeira e mineração. As diferentes facções estabelecem alianças e rivalidades com grupos locais e regionais, contribuindo para uma instabilidade crescente.

Ainda na esfera da atuação das organizações criminosas, o trabalho de @couto_relacoes_2024 foca nas relações transfronteiriças do narcotráfico na Amazônia, destacando como as redes de tráfico de drogas e outras atividades, como o garimpo ilegal, se entrelaçam e impactam diretamente a segurança da região. Couto enfatiza que o narcotráfico não só utiliza o território amazônico como rota de passagem, mas também se integra à economia local, explorando recursos naturais e contribuindo para o aumento da violência e da criminalidade.

Esse entendimento é relevante para a segurança pública no arco Norte, pois demonstra como a região se torna vulnerável devido à presença de facções criminosas que competem pelo controle de rotas de tráfico e áreas de exploração. Também aborda a necessidade de uma cooperação pan-amazônica, envolvendo o Brasil e países vizinhos, para implementar uma estratégia de segurança integrada e coordenada, capaz de responder às ameaças transnacionais que afetam diretamente a soberania e o desenvolvimento local.

O arco Central abrange uma região de grande diversidade geográfica, por se encontrar na zona de transição entre a Amazônia e o Centro-Sul do país. @moura_referencias_2018, ao analisar os arranjos transfronteiriços brasileiros, mostra que o arco Central tem sido fortemente impactado pelo avanço da fronteira econômica (principalmente a agrícola) e pelo deslocamento para a região de grandes empresas do Sul. Contudo, o que mais marca essa faixa de fronteira é a conjunção de uma série de ilícitos e atos de violência. No Mato Grosso e Mato Grosso do Sul, registra-se o maior número de apreensões de drogas, evidenciando a existência de grandes “corredores” por onde passam os maiores fluxos do tráfico. Em outros estados fronteiriços, pode predominar o tráfico “formiga,” mais difícil de ser apreendido devido à multiplicidade de rotas e pequenas quantidades traficadas.

Já no arco Sul, a particularidade está em seu desempenho econômico e urbano, maior do que nas outras duas regiões. Sua fronteira possui muito mais presença das forças de segurança e é altamente regulada. Similar ao arco Central, apresenta problemas de tráfico devido ao elevado grau de integração com os países vizinhos; entretanto, esse problema se soma ao aumento do contrabando. @andrade_politicas_2019 caracteriza a região, destacando o potencial para o desenvolvimento da segurança pública na fronteira brasileira em geral.

## Impacto da presença militar e segurança pública

Diante do apresentado, do ponto de vista legal e da conjuntura de segurança pública da região, a presença das Forças Armadas na faixa de fronteira tem potencial para impactar a segurança pública e o desenvolvimento local. Andrade et al. (2019) descrevem como o Exército está envolvido em missões que vão além da defesa nacional tradicional, como ações de segurança pública e combate ao crime nas fronteiras. O documento destaca que as operações militares visam não apenas a segurança, mas também o desenvolvimento social e econômico em áreas de fronteira. Isso fornece uma perspectiva sobre os efeitos indiretos da presença militar, que vão além da simples redução de crimes violentos.

Andrade et al. (2019) classificam o panorama atual das operações em políticas de defesa e políticas de segurança pública. No que diz respeito à defesa, o trabalho apresenta o Programa Calha Norte (PCN), o Sistema Integrado de Monitoramento de Fronteiras (Sisfron), a Operação Ágata e a Política Nacional de Defesa (PND), que acompanha a Estratégia Nacional de Defesa (END). O PCN é o mais antigo, criado em 1985 pelo governo federal; inicialmente, sua vertente militar tinha maior relevância. O programa passou por atualizações e, em um contexto de redemocratização, a partir de 2005, ele "passou a obter mais recursos financeiros, proporcionando ao programa uma natureza mais social" (Andrade et al., 2019, p.394). Ações de assistência social também são executadas no contexto da Operação Ágata, "nas ações cívico-sociais (ACISO)[...] quando a população é atendida por médicos, dentistas, assistentes sociais e barbeiros, entre outros; quando os fronteiriços recebem medicamentos, documentos, além de corte de cabelo; quando escolas e postos de saúde das localidades são pintados ou reformados" (Figueiredo, 2017, p.77).

Quanto às políticas de segurança pública, Andrade et al. (2019) apresentam o Projeto Unidades Especializadas de Fronteiras (Pefron), o Plano Estratégico de Fronteiras (PEF), a Estratégia Nacional de Segurança Pública nas Fronteiras (Enafron) e o Programa de Proteção Integrada de Fronteiras (PPIF). A criação do Pefron ocorreu em 2008 como uma primeira iniciativa para fomentar e aperfeiçoar a atuação dos órgãos de segurança pública. O projeto foi então encerrado e incorporado à Enafron, no contexto do PEF, em 2011. No final de 2016, ocorreu a atualização do PEF com o lançamento do PPIF. A evolução dos programas apresentada no trabalho mostra que a segurança pública na fronteira sofre de desarticulação. Os autores observam que não existe um plano nacional de segurança pública com metas claras e recursos garantidos, o que compromete a eficácia das políticas, particularmente nas regiões de fronteira. A falta de continuidade das políticas e o panorama alarmante da violência são apresentados como consequências dessa desarticulação.

Vale notar que, apesar da segurança jurídica que rege a situação da segurança pública, a principal necessidade é uma execução clara e organizada dos objetivos para reduzir os problemas de segurança pública na fronteira. Essa execução poderia ser pautada por meio de indicadores produzidos e acompanhados por diversos órgãos além das Forças Armadas, que, atuando em conjunto, têm capacidade para trazer melhorias nesse aspecto do desenvolvimento social. O Anuário Brasileiro de Segurança Pública e a Secretaria Nacional de Segurança Pública (Senasp) já são capazes de produzir dados sobre a criminalidade em todos os municípios, incluindo aqueles que fazem parte da Faixa de Fronteira. Estudos de natureza quantitativa e empírica são essenciais para orientar a execução de políticas de segurança pública, pois fornecem dados concretos que permitem avaliar a eficácia das ações implementadas, identificar áreas críticas e ajustar as estratégias de acordo com as necessidades reais das regiões de fronteira.

## Contriubições do estudo
