---
format: pdf

# misc
lang: pt-BR # siga o padrão: pt-BR, es-AR, en-US etc.
editor: source
---

# Metodologia

## Desenho da pesquisa

O presente estudo é caracterizado como quasi-experimental, ou estudo observacional com abordagem de causalidade. Esse tipo de estudo busca entender relações de causa e efeito, mas sem manipulação direta ou randomização total das variáveis. Em estudos experimentais puros envolve alto grau de controle e os participantes da amostra são alocados de forma aleatória. Nos estudos sociais de natureza quantitativa é muito difícil realizar um experimento controlado com amostra completamente aleatória. No caso, como o fenômeno de interesse é o pertencimento à faixa de fronteira, não é possível designar aleatoriamente municípios com e sem tratamento. Portanto, serão utilizados dados municipais recolhidos de diferentes fontes com variáveis de interesse em um determinado ponto no tempo e a partir da análise desses dados, através de modelos economètricos, pode-se estabelecer uma relação de causalidade.

Portanto, este estudo é quasi-experimental, uma vez que não há controle direto sobre quais municípios recebem o "tratamento" (o pertencimento à Faixa de Fronteira), mas sim observa os efeitos desse fator em contextos já estabelecidos, ajustando para fatores externos.

## Modelo de Regressão Descontínua (RD)

O modelo de Regressão Descontínua é uma metodologia de análise causal amplamente utilizada em contextos não-experimentais, onde a alocação de um tratamento ou intervenção depende de um ponto de corte claramente definido em uma variável contínua. De acordo com @imbens_regression_2007, a RD é poderosa para inferências causais, pois compara unidades logo acima e abaixo do ponto de corte, minimizando o impacto de fatores externos. Essa abordagem é particularmente útil quando uma randomização direta não é viável, mas ainda permite avaliar o efeito de uma intervenção ao observar uma descontinuidade no resultado em função da variável de corte.

@cattaneo_regression_2022 complementam essa discussão ao ampliar o leque de aplicações da RD e oferecer uma revisão mais atualizada dos avanços metodológicos. Eles apresentam duas abordagens principais: o Continuity Framework, que usa regressão polinomial local para capturar a descontinuidade no ponto de corte, e o Local Randomization Framework, que trata a área ao redor do ponto de corte como um experimento aleatório natural. Eles destacam a necessidade de métodos rigorosos de validação e falsificação, incluindo testes de placebo e análise de densidade para garantir a validade dos resultados.

## Dados

### Critérios de seleção

### Tamanho da amostra

## Bases de dados utilizadas

### Sistema de Informação de Mortalidade (SIM)

### Dados Nacionais de Segurança Pública

## Variáveis
